### ISSUE TITLE
pre-trained weights for re-producing results

### ISSUE THREAD

**Issue by sufengniu** [YifeiZhou02/ArCHer#1]
Thank you for the great work, just wondering if you have pre-trained GPT2 weights or Mistral weights released so that I could reproduce results without re-training the model? I know the training script is there already, just wondering, it is fine if you don't want to provide it. Thank you!

**Comment by YifeiZhou02** [comment]
Hi, thanks for being interested in our work! Pre-trained BC checkpoints are provided in the google drive link https://drive.google.com/drive/folders/1pRocQI0Jv479G4vNMtQn1JOq8Shf2B6U?usp=sharing (also in the README). Unfortunately I was not able to save all the checkpoints for the experiments, but most experiments should be able to be replicated within 2-3 days with parallelism on 4 gpus.
