### ISSUE TITLE
Where is detective game

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [YifeiZhou02/ArCHer#15]
Hello,

I would like to inquire about the Detective game environment. When I clicked the link we provided, it took me to the article titled “Interactive Fiction Games: A Colossal Adventure”. Could you please confirm if the Detective game is part of the Jericho Environment mentioned in this article? Also, are there any additional resources I need to download to proceed?

Thank you!

**Comment by YifeiZhou02** [comment]
Hi, yes this the correct paper. You can also find the detective game included here: https://github.com/YifeiZhou02/ArCHer/blob/master/dataset/detective.z5
