### ISSUE TITLE
Please tell me, after I complete the detective game task, how can I reset the new task?

### ISSUE THREAD

**Issue by SakuraXiaMF** [YifeiZhou02/ArCHer#16]
`import copy
import random
from jericho import *
# Create the environment, optionally specifying a random seed
env = FrotzEnv("z-machine-games-master/jericho-game-suite/detective.z5")
observation, info = env.reset()
init=copy.deepcopy(observation)
`
when i download detective.z5, i finish the first detective game, i want to another task.
I user env.reset(), but i don't get a new task

**Comment by YifeiZhou02** [comment]
Thanks for your interest. Currently in our experiments with jericho, we only consider one task environment which is detective. Feel free to update the code to support multi-tasking on more jericho environments.

**Comment by SakuraXiaMF** [comment]
Thanks for your replay. Does the "detective task" only have one task? it doesn't like Webshop have many instructions?

**Comment by YifeiZhou02** [comment]
yes it only has one task and does not have multiple instructions
