### ISSUE TITLE
这个工作可以直接用于LLama2么

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [YifeiZhou02/ArCHer#2]

**Comment by YifeiZhou02** [comment]
Hi,

Thanks for your interest in our work. We have existing scripts for running Mistral-7B. To use LLama2, simply make a different prompt template as in [here](https://github.com/YifeiZhou02/ArCHer/tree/master/archer/prompts), and change the policy lm [here](https://github.com/YifeiZhou02/ArCHer/blob/master/scripts/config/archer_llm_20q.yaml#L15). We found the performance of LLama2-7B to be much worse than Mistral-7B. We did not test LLama2 with more parameters.
