### ISSUE TITLE
请问我们的工作中，对于webshop的训练有提前进行SFT模型么？

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [YifeiZhou02/ArCHer#4]
请问我们的工作中，对于webshop的训练有提前进行SFT模型么？

**Comment by YifeiZhou02** [comment]
Yes, it is in the provided google drive link in the README.

**Comment by DZ9** [comment]
Is _gpt2_bc_workshop_history.pt_ the sft model for webshop? Does it means I need to load the model for training acther in rl step? How can I train a new sft model with different base LLM like Llama2? Thanks.
