### ISSUE TITLE
WebShop Experiment

### ISSUE THREAD

**Issue by symoon11** [YifeiZhou02/ArCHer#6]
Thank you for the great work! I have some questions regarding on the WebShop experiment.

1. Does the policy trained on 100 environments transfer well to held-out environments?
2. Have you attempted to train a policy on more than 100 environments? I understand that the speed of environment interaction might be slower, but I am curious about the results.

Thanks.

**Comment by YifeiZhou02** [comment]
Thanks for your question. We actually did not try held-out environment, but we did try running on 1000 webshop environments. The agent indeed seems to improving. However, for some unknown reason of the webshop server, it seems to be extremely slow when there are 1000 possible instructions so we did not report it in the paper. Hope it helps!

**Comment by symoon11** [comment]
Thanks for your reply! I resolved the speed issue yesterday. Currently, I am running PPO and your algorithm on 1000 environments and it seems there is still room for improvement. Can I email you to learn more about the WebShop experiment?

**Comment by YifeiZhou02** [comment]
Of course.

**Comment by moghis** [comment]
> Thanks for your reply! I resolved the speed issue yesterday. Currently, I am running PPO and your algorithm on 1000 environments and it seems there is still room for improvement. Can I email you to learn more about the WebShop experiment?

Hello  @symoon11, Can you please share your adjusted code? I would like to know how you resolved the issue.
Thank you very much.

**Comment by symoon11** [comment]
Just comment out lines 237 to 250 in https://github.com/princeton-nlp/WebShop/blob/a557a208d03b93c83f4075e66e8746922606e60f/web_agent_site/app.py to speed up!

**Comment by destinyyzy** [comment]
> Just comment out lines 237 to 250 in https://github.com/princeton-nlp/WebShop/blob/a557a208d03b93c83f4075e66e8746922606e60f/web_agent_site/app.py to speed up!

Not sure if you have tried running PPO on more data(10000 instructions)? After I adopted your speed optimization method, the sampling speed was still very slow when training on 10,000 instructions.

**Comment by symoon11** [comment]
I am not currently working on Webshop, so my answer may not be entirely accurate. Please disable all logging in the Webshop environment by running the script without using the `--log` flag.

Additionally, running PPO on 10,000 instances would not work well. It would likely only achieve around 60% generalization performance.
